/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:6360da69-d23f-4cac-8afb-1c44c18fe0a4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Usx18TixI",
    "aws_user_pools_web_client_id": "54460r47mieqhnf37vggnrdl5m",
    "oauth": {}
};


export default awsmobile;
