/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:6360da69-d23f-4cac-8afb-1c44c18fe0a4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Usx18TixI",
    "aws_user_pools_web_client_id": "54460r47mieqhnf37vggnrdl5m",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://meaumarl4vaydb3foay3qya65a.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-kfxvgtvmk5aylhhy56ttnyev3q",
    "aws_user_files_s3_bucket": "amplifyapp29480c87e2454765ae1e5e50e7fcc007112224-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
